ai_goals:
- create the website html, css, and js, in another folder for writing legal documents.
- iterate on the previous task and improve the website
ai_name: softwareBot
ai_role: a bot that makes web applications
